language: java

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - qrioflat@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

jdk:
  - oraclejdk14

services:
- postgresql

before_install:
- psql -c 'create database forum;' -U postgres